<?php

namespace Database\Seeders;

use App\Models\Word;
use Illuminate\Database\Seeder;

class WordSeeder extends Seeder
{
    private array $words = [
        ['word' => 'Айтос', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Асеновград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ахтопол', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Балчик', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Банкя', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Банско', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Батак', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Белене', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Белица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Белослав', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Берковица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Битоля', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Благоевград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ботевград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Брацигово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Брезник', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Бургас', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Варна', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Велес', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Велики Преслав', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Велико Търново', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Велинград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Видин', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Враца', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Вършец', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Габрово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Гевгели', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Горна Оряховица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Гоце Делчев', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Гюмюрджина', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Дедеагач', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Демир Хисар', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Димитровград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Добрич', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Дойран', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Долна Баня', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Долна Оряховица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Долни Дъбник', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Драма', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Дупница', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Елена', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Исперих', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ихтиман', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кавала', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Каварна', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Казанлък', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Калофер', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Карлово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Карнобат', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кешан', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Китен', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Козлодуй', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Копривщица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Костенец', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Костур', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Котел', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кресна', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Крушево', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ксанти', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кукуш', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кърджали', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Кюстендил', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Лерин', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ловеч', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Лозенград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Бургас', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Мадан', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Мелник', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Момчилград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Монтана', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Несебър', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Никопол', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Нова Загора', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Обзор', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Одрин', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Оряхово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Охрид', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Павликени', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Пазарджик', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Панагюрище', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Перник', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Перущица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Петрич', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Пещера', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Пирдоп', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Плевен', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Пловдив', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Поморие', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Попово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Пордим', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Правец', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Прилеп', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Приморско', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Провадия', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Първомай', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Радомир', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Разград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Разлог', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Самоков', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Сандански', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Свиленград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Свищов', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Своге', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Севлиево', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Серес', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Силистра', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Симеоновград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Скопие', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Сливен', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Смолян', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Созопол', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Солун', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Сопот', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'София', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Стара Загора', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Стражица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Струга', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Струмица', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Тетово', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Тополовград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Троян', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Тулча', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Тутракан', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Търговище', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Харманли', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Хасково', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Хисар', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Царево', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Цариброд', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Цариград', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Чаталджа', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Чепеларе', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Червен бряг', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Чирпан', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Чорлу', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Шумен', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Якоруда', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Ямбол', 'description' => 'град в България', 'category_id' => 1],
        ['word' => 'Печка', 'description' => 'кухненски уред', 'category_id' => 2],
        ['word' => 'Стерео уредба', 'description' => 'ел. техника', 'category_id' => 2],
        ['word' => 'Телевизор', 'description' => 'ел. техника', 'category_id' => 2],
        ['word' => 'Канапе', 'description' => 'мебел', 'category_id' => 2],
        ['word' => 'Канален Сом', 'description' => 'дънна риба', 'category_id' => 3],
        ['word' => 'Бяла Риба', 'description' => 'хищна риба', 'category_id' => 3],
        ['word' => 'Таранка', 'description' => 'мирна риба', 'category_id' => 3],
        ['word' => 'Шаран', 'description' => 'мирна риба', 'category_id' => 3],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Word::insert($this->words);
    }
}
